<a href="https://colab.research.google.com/github/Harsh-Y99/ML-PROJECTS/blob/main/Movie_Recommendation_System_using_Machine_Learning_with_Python_techaintern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [6]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/movies.csv')

In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [7]:
# number of rows and columns in the data frame

movies_data.shape

(4803, 24)

In [ ]:
# selecting the relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [10]:
# combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [11]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799                                                  NaN
4800                                                  NaN
4801                                                  NaN
4802                                                  NaN
Length: 4803, dtype: object


In [12]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [15]:
combined_features = combined_features.dropna()
feature_vectors = vectorizer.fit_transform(combined_features)

In [16]:
print(feature_vectors)

  (0, 2059)	0.1701479649518548
  (0, 6661)	0.11429421237668091
  (0, 11113)	0.19659464365709167
  (0, 8725)	0.16231873789167722
  (0, 7469)	0.23688181493087848
  (0, 12479)	0.1528997976336656
  (0, 14239)	0.19539014255433562
  (0, 12000)	0.20190521307222728
  (0, 11358)	0.2208017329558662
  (0, 14773)	0.20823298735110954
  (0, 14551)	0.2329808254780701
  (0, 11385)	0.14977293661066507
  (0, 9805)	0.26936700729904856
  (0, 9534)	0.08734535805520414
  (0, 14542)	0.12593255607069875
  (0, 13042)	0.0662280667693844
  (0, 4238)	0.23688181493087848
  (0, 12186)	0.2139246902011623
  (0, 2744)	0.25244839623226556
  (0, 14165)	0.1263712397025473
  (0, 12278)	0.33706405674362216
  (0, 5016)	0.16231873789167722
  (0, 2603)	0.2234527578396162
  (0, 3151)	0.2183472672840518
  (0, 4672)	0.10162340157558672
  :	:
  (3756, 6649)	0.1630164373294472
  (3756, 8312)	0.16780336056424186
  (3756, 7615)	0.18714779291826822
  (3756, 2219)	0.14997884476607481
  (3756, 3621)	0.14997884476607481
  (3756, 7262)	0

Cosine Similarity

In [17]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [18]:
print(similarity)

[[1.         0.06798628 0.03717966 ... 0.00395593 0.01660447 0.0321408 ]
 [0.06798628 1.         0.03129961 ... 0.01041746 0.         0.00377777]
 [0.03717966 0.03129961 1.         ... 0.         0.         0.01083266]
 ...
 [0.00395593 0.01041746 0.         ... 1.         0.00252605 0.01171968]
 [0.01660447 0.         0.         ... 0.00252605 1.         0.00319347]
 [0.0321408  0.00377777 0.01083266 ... 0.01171968 0.00319347 1.        ]]


In [19]:
print(similarity.shape)

(3757, 3757)


Getting the movie name from the user

In [20]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : robot


In [21]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [22]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Robots', 'Hoot', 'I, Robot']


In [23]:
close_match = find_close_match[0]
print(close_match)

Robots


In [24]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

441


In [25]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.005851145122238461), (1, 0.005136096553507779), (2, 0.02674435016094931), (3, 0.03891329500790105), (4, 0.005682763703089817), (5, 0.00612696914692618), (6, 0.015690249060512956), (7, 0.05295554948573648), (8, 0.0), (9, 0.0057982382670712755), (10, 0.045800397511996806), (11, 0.006015822334566747), (12, 0.005392712899421799), (13, 0.005844370184682471), (14, 0.014860145203902074), (15, 0.04252073265776373), (16, 0.005744000030829982), (17, 0.005637284138533469), (18, 0.020144651269511635), (19, 0.005874934411211898), (20, 0.004953367747407884), (21, 0.015631789903958623), (22, 0.0), (23, 0.008717555174019275), (24, 0.039759595986439786), (25, 0.006107209023854922), (26, 0.010264535019969533), (27, 0.011214222899579037), (28, 0.05010147623744506), (29, 0.005956814117987563), (30, 0.005792005272989582), (31, 0.0), (32, 0.0678021625725946), (33, 0.020110270915835973), (34, 0.041914029785130286), (35, 0.0055964773264405515), (36, 0.020162258576138594), (37, 0.006002500086804013), (3

In [26]:
len(similarity_score)

3757

In [27]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(441, 1.0), (297, 0.176901607169925), (3717, 0.15756574922763444), (157, 0.15640945292656022), (507, 0.1532505086777923), (537, 0.14466813365882894), (2023, 0.14263029669338284), (1277, 0.13147354109330334), (205, 0.12863651517650782), (880, 0.12786591230430666), (731, 0.12683131299671108), (548, 0.1266359225197496), (1028, 0.11522336094081048), (2005, 0.10815474163531533), (2692, 0.10742788155878387), (926, 0.1010576392089481), (3693, 0.10093911850811782), (553, 0.09795737529472227), (467, 0.09782748305159913), (1484, 0.09751727816863795), (172, 0.09707556857583967), (981, 0.09695025950617782), (1623, 0.09670229197375935), (3172, 0.09579708043599741), (2171, 0.0951853717155946), (403, 0.09481004460931707), (1062, 0.09428185997099875), (1048, 0.09383928669001156), (239, 0.09210111095239547), (685, 0.09098123338261166), (545, 0.08915359016346334), (195, 0.08906031405075245), (1581, 0.08840575798949754), (1571, 0.08799030180250678), (3386, 0.08671300204469944), (210, 0.08661659448175871

In [28]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Robots
2 . Blood Diamond
3 . After.Life
4 . Exodus: Gods and Kings
5 . Independence Day
6 . Immortals
7 . The Animal
8 . Delgo
9 . Sherlock Holmes: A Game of Shadows
10 . Grindhouse
11 . The Jackal
12 . Snake Eyes
13 . Solaris
14 . The Longshots
15 . Thinner
16 . Garfield
17 . Out of the Blue
18 . The Kingdom
19 . Mighty Joe Young
20 . Snakes on a Plane
21 . The Twilight Saga: Breaking Dawn - Part 2
22 . Man of the House
23 . Get on Up
24 . The Contender
25 . My Best Friend's Girl
26 . Last Action Hero
27 . A Bug's Life
28 . The Bucket List
29 . Gravity


Movie Recommendation Sytem

In [35]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you😊 : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : robots
Movies suggested for you😊 : 

1 . Robots
2 . Blood Diamond
3 . After.Life
4 . Exodus: Gods and Kings
5 . Independence Day
6 . Immortals
7 . The Animal
8 . Delgo
9 . Sherlock Holmes: A Game of Shadows
10 . Grindhouse
11 . The Jackal
12 . Snake Eyes
13 . Solaris
14 . The Longshots
15 . Thinner
16 . Garfield
17 . Out of the Blue
18 . The Kingdom
19 . Mighty Joe Young
20 . Snakes on a Plane
21 . The Twilight Saga: Breaking Dawn - Part 2
22 . Man of the House
23 . Get on Up
24 . The Contender
25 . My Best Friend's Girl
26 . Last Action Hero
27 . A Bug's Life
28 . The Bucket List
29 . Gravity
